/***** DO NOT EDIT THIS FILE *****/
// FeatureTests.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var FeatureTests = {};

/*** script -- ListClicks ***/
FeatureTests.ListClicks = function(app) {
	MT.Script.call(this, app, "ListClicks.mt");
};

FeatureTests.ListClicks.prototype = new MT.Script;

FeatureTests.ListClicks.prototype.call = function() {
	//run: ListClicks.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.listClicks = function() {
	return new FeatureTests.ListClicks(this);
};

